// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layouts/Current.tsx": () => import("../components/mockups/home-layouts/Current.tsx"),
  "./components/mockups/home-layouts/Progressive.tsx": () => import("../components/mockups/home-layouts/Progressive.tsx"),
  "./components/mockups/home-layouts/TwoColumn.tsx": () => import("../components/mockups/home-layouts/TwoColumn.tsx")
};
